//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



public partial class TSDataContext : Microsoft.SharePoint.Linq.DataContext {
	
	#region Extensibility Method Definitions
	partial void OnCreated();
	#endregion
	
	public TSDataContext(string requestUrl) : 
			base(requestUrl) {
		this.OnCreated();
	}
	
	/// <summary>
	/// Biblioteka stylów umożliwia przechowywanie arkuszy stylów (na przykład plików CSS czy XSL). Arkusze stylów w tej galerii są dostępne do użytku przez tę witrynę i jej podwitryny.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Biblioteka stylów")]
	public Microsoft.SharePoint.Linq.EntityList<Document> BibliotekaStylów {
		get {
			return this.GetList<Document>("Biblioteka stylów");
		}
	}
	
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Karty pracy")]
	public Microsoft.SharePoint.Linq.EntityList<KartyPracyKartaPracy> KartyPracy {
		get {
			return this.GetList<KartyPracyKartaPracy>("Karty pracy");
		}
	}
	
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Klienci")]
	public Microsoft.SharePoint.Linq.EntityList<KlienciKlient> Klienci {
		get {
			return this.GetList<KlienciKlient>("Klienci");
		}
	}
	
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Raporty")]
	public Microsoft.SharePoint.Linq.EntityList<Raport> Raporty {
		get {
			return this.GetList<Raport>("Raporty");
		}
	}
}

/// <summary>
/// Create a new list item.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Item", Id="0x01")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Document))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(KartaPracy))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Klient))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Raport))]
public partial class Item : Microsoft.SharePoint.Linq.ITrackEntityState, Microsoft.SharePoint.Linq.ITrackOriginalValues, System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging {
	
	private System.Nullable<int> _id;
	
	private System.Nullable<int> _version;
	
	private string _path;
	
	private Microsoft.SharePoint.Linq.EntityState _entityState;
	
	private System.Collections.Generic.IDictionary<string, object> _originalValues;
	
	private string _title;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion

	Microsoft.SharePoint.Linq.EntityState Microsoft.SharePoint.Linq.ITrackEntityState.EntityState {
		get {
			return this._entityState;
		}
		set {
			if ((value != this._entityState)) {
				this._entityState = value;
			}
		}
	}

	System.Collections.Generic.IDictionary<string, object> Microsoft.SharePoint.Linq.ITrackOriginalValues.OriginalValues {
		get {
			if ((null == this._originalValues)) {
				this._originalValues = new System.Collections.Generic.Dictionary<string, object>();
			}
			return this._originalValues;
		}
	}
	
	public Item() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ID", Storage="_id", ReadOnly=true, FieldType="Counter")]
	public System.Nullable<int> Id {
		get {
			return this._id;
		}
		set {
			if ((value != this._id)) {
				this.OnPropertyChanging("Id", this._id);
				this._id = value;
				this.OnPropertyChanged("Id");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="owshiddenversion", Storage="_version", ReadOnly=true, FieldType="Integer")]
	public System.Nullable<int> Version {
		get {
			return this._version;
		}
		set {
			if ((value != this._version)) {
				this.OnPropertyChanging("Version", this._version);
				this._version = value;
				this.OnPropertyChanged("Version");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="FileDirRef", Storage="_path", ReadOnly=true, FieldType="Lookup", IsLookupValue=true)]
	public string Path {
		get {
			return this._path;
		}
		set {
			if ((value != this._path)) {
				this.OnPropertyChanging("Path", this._path);
				this._path = value;
				this.OnPropertyChanged("Path");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Title", Storage="_title", Required=true, FieldType="Text")]
	public virtual string Title {
		get {
			return this._title;
		}
		set {
			if ((value != this._title)) {
				this.OnPropertyChanging("Title", this._title);
				this._title = value;
				this.OnPropertyChanged("Title");
			}
		}
	}
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	protected virtual void OnPropertyChanged(string propertyName) {
		if ((null != this.PropertyChanged)) {
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	protected virtual void OnPropertyChanging(string propertyName, object value) {
		if ((null == this._originalValues)) {
			this._originalValues = new System.Collections.Generic.Dictionary<string, object>();
		}
		if ((false == this._originalValues.ContainsKey(propertyName))) {
			this._originalValues.Add(propertyName, value);
		}
		if ((null != this.PropertyChanging)) {
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
}

/// <summary>
/// Create a new document.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Document", Id="0x0101")]
public partial class Document : Item {
	
	private string _name;
	
	private string _documentModifiedBy;
	
	private string _documentCreatedBy;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Document() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="FileLeafRef", Storage="_name", Required=true, FieldType="File")]
	public string Name {
		get {
			return this._name;
		}
		set {
			if ((value != this._name)) {
				this.OnPropertyChanging("Name", this._name);
				this._name = value;
				this.OnPropertyChanged("Name");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Modified_x0020_By", Storage="_documentModifiedBy", ReadOnly=true, FieldType="Text")]
	public string DocumentModifiedBy {
		get {
			return this._documentModifiedBy;
		}
		set {
			if ((value != this._documentModifiedBy)) {
				this.OnPropertyChanging("DocumentModifiedBy", this._documentModifiedBy);
				this._documentModifiedBy = value;
				this.OnPropertyChanged("DocumentModifiedBy");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Created_x0020_By", Storage="_documentCreatedBy", ReadOnly=true, FieldType="Text")]
	public string DocumentCreatedBy {
		get {
			return this._documentCreatedBy;
		}
		set {
			if ((value != this._documentCreatedBy)) {
				this.OnPropertyChanging("DocumentCreatedBy", this._documentCreatedBy);
				this._documentCreatedBy = value;
				this.OnPropertyChanged("DocumentCreatedBy");
			}
		}
	}
}

/// <summary>
/// Create a new list item.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Karta pracy", Id="0x01005BAEF6D89BFA7841BC45E6613CC823B1")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(KartyPracyKartaPracy))]
public partial class KartaPracy : Item {
	
	private System.Nullable<System.DateTime> _dataRejestracji;
	
	private System.Nullable<double> _czas;
	
	private string _okres;
	
	private string _opis;
	
	private string _kontakt;
	
	private System.Nullable<bool> _rozliczony;
	
	private string _ostatniaAktualizacja;
	
	private Microsoft.SharePoint.Linq.EntityRef<KlienciKlient> _klient;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public KartaPracy() {
		this._klient = new Microsoft.SharePoint.Linq.EntityRef<KlienciKlient>();
		this._klient.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<KlienciKlient>>(this.OnKlientSync);
		this._klient.OnChanged += new System.EventHandler(this.OnKlientChanged);
		this._klient.OnChanging += new System.EventHandler(this.OnKlientChanging);
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="colData", Storage="_dataRejestracji", Required=true, FieldType="DateTime")]
	public System.Nullable<System.DateTime> DataRejestracji {
		get {
			return this._dataRejestracji;
		}
		set {
			if ((value != this._dataRejestracji)) {
				this.OnPropertyChanging("DataRejestracji", this._dataRejestracji);
				this._dataRejestracji = value;
				this.OnPropertyChanged("DataRejestracji");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="colCzasMin", Storage="_czas", Required=true, FieldType="Number")]
	public System.Nullable<double> Czas {
		get {
			return this._czas;
		}
		set {
			if ((value != this._czas)) {
				this.OnPropertyChanging("Czas", this._czas);
				this._czas = value;
				this.OnPropertyChanged("Czas");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="colOkres", Storage="_okres", IsCalculated=true, FieldType="Text")]
	public virtual string Okres {
		get {
			return this._okres;
		}
		set {
			if ((value != this._okres)) {
				this.OnPropertyChanging("Okres", this._okres);
				this._okres = value;
				this.OnPropertyChanged("Okres");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="colOpis", Storage="_opis", FieldType="Note")]
	public string Opis {
		get {
			return this._opis;
		}
		set {
			if ((value != this._opis)) {
				this.OnPropertyChanging("Opis", this._opis);
				this._opis = value;
				this.OnPropertyChanged("Opis");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="colKontakt", Storage="_kontakt", FieldType="Text")]
	public string Kontakt {
		get {
			return this._kontakt;
		}
		set {
			if ((value != this._kontakt)) {
				this.OnPropertyChanging("Kontakt", this._kontakt);
				this._kontakt = value;
				this.OnPropertyChanged("Kontakt");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="colCzyRozliczony", Storage="_rozliczony", FieldType="Boolean")]
	public virtual System.Nullable<bool> Rozliczony {
		get {
			return this._rozliczony;
		}
		set {
			if ((value != this._rozliczony)) {
				this.OnPropertyChanging("Rozliczony", this._rozliczony);
				this._rozliczony = value;
				this.OnPropertyChanged("Rozliczony");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="colOstatniaDataRaportowania", Storage="_ostatniaAktualizacja", FieldType="Text")]
	public virtual string OstatniaAktualizacja {
		get {
			return this._ostatniaAktualizacja;
		}
		set {
			if ((value != this._ostatniaAktualizacja)) {
				this.OnPropertyChanging("OstatniaAktualizacja", this._ostatniaAktualizacja);
				this._ostatniaAktualizacja = value;
				this.OnPropertyChanged("OstatniaAktualizacja");
			}
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Title {
		get {
			throw new System.InvalidOperationException("Field Title was removed from content type Karta pracy.");
		}
		set {
			throw new System.InvalidOperationException("Field Title was removed from content type Karta pracy.");
		}
	}
	
	[Microsoft.SharePoint.Linq.AssociationAttribute(Name="selKlient_Selector", Storage="_klient", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="Klienci")]
	public KlienciKlient Klient {
		get {
			return this._klient.GetEntity();
		}
		set {
			this._klient.SetEntity(value);
		}
	}
	
	private void OnKlientChanging(object sender, System.EventArgs e) {
		this.OnPropertyChanging("Klient", this._klient.Clone());
	}
	
	private void OnKlientChanged(object sender, System.EventArgs e) {
		this.OnPropertyChanged("Klient");
	}
	
	private void OnKlientSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<KlienciKlient> e) {
		if ((Microsoft.SharePoint.Linq.AssociationChangedState.Added == e.State)) {
			e.Item.KartaPracy.Add(this);
		}
		else {
			e.Item.KartaPracy.Remove(this);
		}
	}
}

/// <summary>
/// Create a new list item.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Klient", Id="0x01002F114D5ABAECBF4FBB02EFE903AA3059")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(KlienciKlient))]
public partial class Klient : Item {
	
	private string _nazwaKlienta;
	
	private string _kontakt;
	
	private string _email;
	
	private string _cC;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Klient() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="colNazwaKlienta", Storage="_nazwaKlienta", Required=true, FieldType="Text")]
	public string NazwaKlienta {
		get {
			return this._nazwaKlienta;
		}
		set {
			if ((value != this._nazwaKlienta)) {
				this.OnPropertyChanging("NazwaKlienta", this._nazwaKlienta);
				this._nazwaKlienta = value;
				this.OnPropertyChanged("NazwaKlienta");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="colKontakt", Storage="_kontakt", FieldType="Text")]
	public string Kontakt {
		get {
			return this._kontakt;
		}
		set {
			if ((value != this._kontakt)) {
				this.OnPropertyChanging("Kontakt", this._kontakt);
				this._kontakt = value;
				this.OnPropertyChanged("Kontakt");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="colEmail", Storage="_email", Required=true, FieldType="Text")]
	public string Email {
		get {
			return this._email;
		}
		set {
			if ((value != this._email)) {
				this.OnPropertyChanging("Email", this._email);
				this._email = value;
				this.OnPropertyChanged("Email");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="colCC", Storage="_cC", FieldType="Text")]
	public string CC {
		get {
			return this._cC;
		}
		set {
			if ((value != this._cC)) {
				this.OnPropertyChanging("CC", this._cC);
				this._cC = value;
				this.OnPropertyChanged("CC");
			}
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Title {
		get {
			throw new System.InvalidOperationException("Field Title was removed from content type Klient.");
		}
		set {
			throw new System.InvalidOperationException("Field Title was removed from content type Klient.");
		}
	}
}

/// <summary>
/// Create a new list item.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Raport", Id="0x01006D2721F52EB8FF41AD70CAFB2F0DACFA")]
public partial class Raport : Item {
	
	private string _opisRaportu;
	
	private string _uwagi;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Raport() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="colOpisRaportu", Storage="_opisRaportu", Required=true, FieldType="Note")]
	public string OpisRaportu {
		get {
			return this._opisRaportu;
		}
		set {
			if ((value != this._opisRaportu)) {
				this.OnPropertyChanging("OpisRaportu", this._opisRaportu);
				this._opisRaportu = value;
				this.OnPropertyChanged("OpisRaportu");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="colUwagi", Storage="_uwagi", FieldType="Note")]
	public string Uwagi {
		get {
			return this._uwagi;
		}
		set {
			if ((value != this._uwagi)) {
				this.OnPropertyChanging("Uwagi", this._uwagi);
				this._uwagi = value;
				this.OnPropertyChanged("Uwagi");
			}
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Title {
		get {
			throw new System.InvalidOperationException("Field Title was removed from content type Raport.");
		}
		set {
			throw new System.InvalidOperationException("Field Title was removed from content type Raport.");
		}
	}
}

/// <summary>
/// Create a new list item.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Karta pracy", Id="0x01005BAEF6D89BFA7841BC45E6613CC823B1", List="Karty pracy")]
public partial class KartyPracyKartaPracy : KartaPracy {
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public KartyPracyKartaPracy() {
		this.OnCreated();
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Okres {
		get {
			throw new System.InvalidOperationException("Field colOkres was removed from content type Karta pracy.");
		}
		set {
			throw new System.InvalidOperationException("Field colOkres was removed from content type Karta pracy.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override System.Nullable<bool> Rozliczony {
		get {
			throw new System.InvalidOperationException("Field colCzyRozliczony was removed from content type Karta pracy.");
		}
		set {
			throw new System.InvalidOperationException("Field colCzyRozliczony was removed from content type Karta pracy.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string OstatniaAktualizacja {
		get {
			throw new System.InvalidOperationException("Field colOstatniaDataRaportowania was removed from content type Karta pracy.");
		}
		set {
			throw new System.InvalidOperationException("Field colOstatniaDataRaportowania was removed from content type Karta pracy.");
		}
	}
}

/// <summary>
/// Create a new list item.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Klient", Id="0x01002F114D5ABAECBF4FBB02EFE903AA3059", List="Klienci")]
public partial class KlienciKlient : Klient {
	
	private string _colKlient_Selector;
	
	private Microsoft.SharePoint.Linq.EntitySet<KartaPracy> _kartaPracy;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public KlienciKlient() {
		this._kartaPracy = new Microsoft.SharePoint.Linq.EntitySet<KartaPracy>();
		this._kartaPracy.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<KartaPracy>>(this.OnKartaPracySync);
		this._kartaPracy.OnChanged += new System.EventHandler(this.OnKartaPracyChanged);
		this._kartaPracy.OnChanging += new System.EventHandler(this.OnKartaPracyChanging);
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="colKlient_Selector", Storage="_colKlient_Selector", ReadOnly=true, IsCalculated=true, FieldType="Text")]
	public string ColKlient_Selector {
		get {
			return this._colKlient_Selector;
		}
		set {
			if ((value != this._colKlient_Selector)) {
				this.OnPropertyChanging("ColKlient_Selector", this._colKlient_Selector);
				this._colKlient_Selector = value;
				this.OnPropertyChanged("ColKlient_Selector");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.AssociationAttribute(Name="selKlient_Selector", Storage="_kartaPracy", ReadOnly=true, MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Backward, List="Karty pracy")]
	public Microsoft.SharePoint.Linq.EntitySet<KartaPracy> KartaPracy {
		get {
			return this._kartaPracy;
		}
		set {
			this._kartaPracy.Assign(value);
		}
	}
	
	private void OnKartaPracyChanging(object sender, System.EventArgs e) {
		this.OnPropertyChanging("KartaPracy", this._kartaPracy.Clone());
	}
	
	private void OnKartaPracyChanged(object sender, System.EventArgs e) {
		this.OnPropertyChanged("KartaPracy");
	}
	
	private void OnKartaPracySync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<KartaPracy> e) {
		if ((Microsoft.SharePoint.Linq.AssociationChangedState.Added == e.State)) {
			e.Item.Klient = this;
		}
		else {
			e.Item.Klient = null;
		}
	}
}
